apiVersion: 1

datasources:
  - name: accounting_es
    type: elasticsearch
    access: proxy
    # database: "[logstash-]xxxx.ww"
    url: http://elasticsearch:9200
    jsonData:
      esVersion: 56
      timeInterval: 1m
      timeField: "@timestamp"
